#!/usr/bin/env bash

set -euo pipefail

##? Setups the environment
#?? 1.0.0
##?
##? Based on codelytv/dotfiles
##? Usage:
##?    install

echo "🚀 Welcome to the youssefmzouri/dotfiles installer!"
echo "---------------------------------------------------"
echo
export DOTFILES_PATH="$HOME/.dotfiles"
echo "👉  Cloning into: '$DOTFILES_PATH'"

# To test that git is installed (if not macOS will prompt an installer)
git --version

git clone --depth 1 git@github.com:youssefmzouri/dotfiles.git "$DOTFILES_PATH"